### ISSUE TITLE
Allow passing a LatLng object

### ISSUE THREAD

**Issue by knownasilya** [cometaworks/ember-cli-google-street-view#16]
Currently it's kind of tedious, since usually when woking with Google Maps you use `google.maps.LatLng` objects, but in this case you have to split up, which requires the following

```js
  lat: computed('roadLatLng', {
    get() {
      var latlng = this.get('roadLatLng');

      if (latlng) {
        return latlng.lat();
      }
    }
  }),

  lng: computed('roadLatLng', {
    get() {
      var latlng = this.get('roadLatLng');

      if (latlng) {
        return latlng.lng();
      }
    }
  }),
```

Just to do `{{street-view lat=model.lat lng=model.lng}}`. Would be nicer if we could do `{{street-view latlng=roadLatLng}}` instead :+1:

**Comment by knownasilya** [comment]
It could accept the following forms: `LatLng`,  `{ lat, lng }` or `[lat, lng]` and could handle the previous syntax with `{{street-view latlng=(hash lat=lat lng=lng)}}`.

This could also be backwards compatible, so you could use either option.

**Comment by FutoRicky** [comment]
This is a very viable feature. Definitely will work on this when I get a chance. Thanks

**Comment by FutoRicky** [comment]
https://github.com/cometaworks/ember-cli-google-street-view/commit/616389589b8cc735c1a6a6baef9ed39b0e19bb57
Addon now supports passing `google.maps.LatLng` object directly to component.
