### ISSUE TITLE
Doesn't want to work in Safari

### ISSUE THREAD

**Issue by knownasilya** [cometaworks/ember-cli-google-street-view#27]
See maldenma.beta.mapgeo.io in safari, and click on one of the brown buildings that is on a streetview road, e.g. https://maldenma.beta.mapgeo.io/properties/074%20261%20101

The expected result is a streetview image, but instead it shows up as grey. All of the methods run, but it just doesn't generate it properly.

**Comment by FutoRicky** [comment]
Could you provide the code to be able to recreate this bug?

**Comment by knownasilya** [comment]
```hbs
{{street-view lat=property.lat lng=property.lng
      width='100%'
      height='100px'
      panControl=false
      zoomControl=false
      linksControl=false
      addressControl=false}}
```
38.046393,-121.25591

**Comment by FutoRicky** [comment]
Tested and working fine on safari. Using Safari v9.0.1
