### ISSUE TITLE
Is possible to set the 'Heading' parameter?

### ISSUE THREAD

**Issue by djq** [cometaworks/ember-cli-google-street-view#30]
Is it possible to set the street view heading via the template?

Currently, I'm including a street view like so:
`{{street-view lat=model.streetview.lat lng=model.streetview.lon}}`

Is it possible to set the heading direction doing something like this?
`{{street-view lat=model.streetview.lat lng=model.streetview.lon heading=model.streetview.heading}}`

Heading [definition](https://developers.google.com/maps/documentation/streetview/intro) from google docs: 
"heading indicates the compass heading of the camera. Accepted values are from 0 to 360 (both values indicating North, with 90 indicating East, and 180 South). If no heading is specified, a value will be calculated that directs the camera towards the specified location, from the point at which the closest photograph was taken."

**Comment by FutoRicky** [comment]
@djq Yes, the `pov` property is actually an object. You assign the values to this property like so:
```
pov: {
  heading: 0,
  pitch: 0,
}
```
Define it in your route's controller and assign it to the component `{{street-view lat=model.lat lng=model.lng pov=pov}}`


 [Docs](https://developers.google.com/maps/documentation/javascript/reference?hl=en#StreetViewPov)
