### ISSUE TITLE
[bug] Subsequent latLng updates don't set lat & lng

### ISSUE THREAD

**Issue by knownasilya** [cometaworks/ember-cli-google-street-view#31]
See https://github.com/cometaworks/ember-cli-google-street-view/blob/master/addon/components/street-view.js#L77

Since `lat` and `lng` are already set from the first `setLatLng`, a second one does not get called.

**Comment by FutoRicky** [comment]
merged 

![](http://media0.giphy.com/media/CvZuv5m5cKl8c/giphy.gif)
